---
- name: Init qredochain data directory and configs
  become_user: "{{ service_name }}"
  ansible.builtin.shell: |
    {{ service_dir }}/{{ service_name }} init --network {{ env }} --snapshot --password {{ qredochain_snapshot_auth }}
  args:
    executable: /bin/bash
  changed_when: true

- name: Configure persistent peers
  ansible.builtin.lineinfile:
    path: "{{ service_dir }}/.{{ service_name }}/{{ env }}/config/config.toml"
    regexp: '^persistent_peers ='
    line: 'persistent_peers = "{{ qredochain_peer_1_id }}@{{ qredochain_sentry_endpoint }}:{{ qredochain_peer_1_port }},{{ qredochain_peer_2_id }}@{{ qredochain_sentry_endpoint }}:{{ qredochain_peer_2_port }}"'
